config/routes.rb
Rails.application.routes.draw do

   root 'static#index'

   resources :users, only: [:new, :show, :create, :edit, :update, :index]
   
   resources :users do
     resources :feeds, only: [:show, :new, :create, :edit, :update]
   end

   resources :users do
     resources :posts, only: [:show, :new, :create, :edit, :update, :index]
   end
   get "feeds" => "feeds#index"
   get "login" => "sessions#new"
   post "login" => "sessions#create"
   delete "logout" => "sessions#destroy"
   get "admin" => "admin#index"

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_many :posts
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :feed
  belongs_to :user
  validates :title, :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  validates :email, presence: true 
  has_secure_password
  has_many :posts
  has_one :feed

  def is_admin?
    self.admin == true
  end

  def can_login?
    self.can_login == true
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def index
    @users = User.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include FeedsHelper
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  def index
    @feeds = Feed.all
  end

  def show
    @user = User.find(params[:user_id])
    @feed = @user.feed
  end

  def new
    @user = User.find(params[:user_id])
    @feed = @user.feed
  end

  def create 
    @feed = current_user.create_feed(feed_params)
    if @feed.save
      flash[:notice] = "Blog created"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Something went wrong!"
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:user_id])
    @feed = @user.feed
  end

  def update
    @user = User.find(params[:user_id])
    @feed = @user.feed
    if @feed.update(feed_params)
      flash[:notice] = "Feed updated!"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Something went wrong!"
      redirect_to root_path
    end
  end

  private

  def feed_params
    params.require(:feed).permit(:user_id, :name, :description, :id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :correct_user, only: [:new, :create, :update, :edit]

  def index
    @user = User.find(params[:user_id])
    @posts = @user.feed.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.feed.posts.find(params[:id])
  end

  def new
    @post = current_user.feed.posts.new 
  end

  def create
    @post = current_user.feed.posts.build(post_params)
    if @post.save
      flash[:notice] = "Post created!"
      redirect_to user_posts_path
    else
      flash[:notice] = "Something went wrong!"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @post = @user.feed.posts.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post updated"
      redirect_to user_posts_path
    else
      flash[:notice] = "Something went wrong!"
      redirect_to root_path
    end
  end

  private

  def correct_user
    @user = User.find(params[:user_id])
    (flash[:notice] = "Not authorized") && redirect_to(root_url) unless @user == current_user
  end

  def post_params
    params.require(:post).permit(:user_id, :title, :body, :id, :user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username(auth_params[:username])
    if user && user.can_login? && user.authenticate(auth_params[:password])
      flash[:notice] = "You have logged in!"
      login(user)
      redirect_to user_path(user)
    elsif user && user.authenticate(auth_params[:password]) && !user.can_login
      flash.now.alert = "Please contact Cody to approve your account."
      render "new"
    else 
      flash.now.alert = "Incorrect username or password."
      render "new"
    end
  end

  def destroy
    log_out
    flash[:notice] = "You have logged out!"
    redirect_to root_path
  end

  private

  def auth_params
    params.require(:session).permit(:user, :user_id, :username, :password, :email)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def index
    render 'index'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.welcome_email(@user).deliver_later
      flash[:notice] = "Account created"
      redirect_to login_path
    else 
      flash[:notice] = "Invalid account information"
      render 'new'
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def show
    if logged_in?
      @user = User.find(params[:id])
    else 
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "Profile updated"
      redirect_to(:back) 
    else
     render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:user, :id, :username, :password,
                                 :password_confirmation, :email, :admin, :can_login) 
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper

 def has_feed?(user)
   !user.feed.nil?
 end 

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/admin/index.html.erb
<h1>Admin Page for ALL DA USERS</h1>
<table class="table table-striped table-bordered">
  <thead>
    <th>Username</th>
    <th>Email</th>
    <th>Can login</th>
    <th>Admin Status</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <%= form_for user, url: user_path(user), method: :patch do |f| %>
          <td><%= f.text_field :username %></td>
          <td><%= f.text_field :email %></td>
          <td><%= f.check_box :can_login %></td>
          <td><%= f.check_box :admin %></td>
          <%= f.submit "Save", :style => "display: none"%>
        <%end%>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/feeds/_form.html.erb
<%= form_for([@user, @feed]) do |f| %>
  <div class="container">
    <div class="form-group">
      <%= f.label :name, :class => "col-sm-2 control-label" %>
      <%= f.text_field :name, :value => @feed.name, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :description, :class => "col-sm-2 control-label" %>
      <%= f.text_area :description, :value => @feed.description, :class => "form-control" %>
    </div>
  <%= f.submit "Submit", :class => "submit-button" %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<%= render 'form' %>

app/views/feeds/index.html.erb
<table class="table table-striped tabled-bordered">
  <thead>
    <th>Name</th>
    <th>Link</th>
  </thead>
  <tbody>
    <% @feeds.each do |feed| %>
      <tr>
        <td><%= feed.name %></td>
        <td><%= link_to "Blog!", user_feed_path(@user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/feeds/new.html.erb
<%= render 'form' %>

app/views/feeds/show.html.erb
<div class="container">
  <div class="text-center"><h1><%= @feed.name %></h1></div>
  <div class="text-center"><h2><%= @feed.description %></h2></div>
</div>

<% @feed.posts.each do |post| %>
  <div class="text-center"><%= link_to "#{post.title}", user_post_path(@user, post)  %></div>
  <div class="text-left body-box"><%= post.body %></div>
  <hr />
<% end %>

<%= link_to "Edit blog info", edit_user_feed_path(@user, @feed), :class => "btn btn-default" if @user == current_user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Partytown</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-inverse">
      <div class="navbar-class">
        <div class="container">
          <!-- Collect the nav links, forms, and other content for toggling -->

          <ul class="nav navbar-nav">
            <li><%= link_to "Homepage", root_path %></li>
            <li><%= link_to "Login", login_path if !logged_in? %></li>
            <li><%= link_to "Logout", logout_path, method: "delete" if logged_in? %></li>
            <li><%= link_to "Profile", user_path(current_user) if logged_in? %></li>
            <li><%= link_to "Admin Page", admin_path if logged_in? && current_user.admin? %></li>
            <li><%= link_to "My Blog", user_feed_path(current_user, current_user.feed) if logged_in? && has_feed?(current_user) %></li>
            <li><%= link_to "Users!", users_path if logged_in? %></li>
          </ul>       
        </div>
      </div>
    </header>

    <div class="container">
      <div class="flash-messages">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, class: "alert alert-info" %>
        <% end %>
      </div>
      <%= yield %>
    </div> 
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for([@user, @post]) do |f| %>
  <div class="container">
    <div class="form-group">
      <%= f.label :title, :class => "col-sm-2 control-label" %>
      <%= f.text_field :title, :value => @post.title, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :body, :class => "col-sm-2 control-label" %>
      <%= f.text_area :body, :value => @post.body, :class => "form-control" %>
    </div>
    <%= f.submit "Submit", :class => "submit-button" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h1><%= @user.feed.name %></h1>
<% @posts.each do |post| %>
  <div class="container">
    <table class="table">
      <tr>
  <div class="h1">
    <%= post.title %>
  </div>
      </tr>
      <tr>
  <p class= "text-left">
  <td><%= post.body %></td>
  </p>
      </tr>
    </table>
    <%= link_to "See this post!", user_post_path(@user, post), :class => "btn btn-default" %>
    <%= link_to "Edit post", edit_user_post_path(@user, post), :class => "btn btn-default" if logged_in? && @user == current_user%>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <h1><%= @post.title %></h1>
  <p class="text-left"><%= @post.body %></p>
  <%= link_to "Edit Post", edit_user_post_path if @post.user == current_user %>
</div>

app/views/users/_form.html.erb
<% @page_title = "User Account Creation" %>
<body>
  <div class="container">
    <%= form_for @user do |form| %>
   <form class="form-inline">
     <div class="row">
       <div class="form-group">
         <%= form.label :username, :class => 'col-sm-2 control-label' %>
         <div class="col-sm-2"> 
           <%= form.text_field :username, :class => 'form-control' %>
         </div>
       </div>
     </div>
     <div class="row">
       <div class="form-group">
         <%= form.label :email, :class => 'col-sm-2 control-label' %>
         <div class="col-sm-2">
           <%= form.text_field :email, :class => 'form-control' %>
         </div>
       </div>
     </div>
     <div class="row">
       <div class="form-group">
         <%= form.label "Password", :class => 'col-sm-2 control-label' %>
         <div class="col-sm-2">
           <%= form.password_field :password, :class => 'form-control' %>
         </div>
       </div>
     </div>
     <div class="row">
       <div class="form-group">
         <%= form.label "Password Confirmation", :class => 'col-sm-2 control-label' %>
         <div class="col-sm-2">
           <%= form.password_field :password_confirmation, :class => 'form-control' %>
         </div>
       </div>
     </div>
     <%= form.submit "Create Account", :class => 'submit-button' %>
   </form>
 <% end %>
  </div>
</body>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="text-center"><h1>Update your profile</h1></div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary submit-button" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users!</h1>
<table class="table table-striped table-bordered">
  <thead>
    <th>Username</th>
    <th>Blog</th>
    <th>Profile</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <% if !user.feed.blank? %>
          <td><%= link_to "User Blog!", user_feed_path(user, user.feed) %></td>
        <% else %>
           <td>PLACEHOLDER</td>
         <% end %>
        <td><%= link_to "Profile!", user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<h1><%= @user.username %>'s account</h1>
<table class="table table-striped table-bordered">
  <thead>
    <th>Username</th>
    <th>Email</th>
    <th>Date Joined</th>
  </thead>
  <tbody>
    <tr>
      <td><%= @user.username %></td>
      <td><%= @user.email %></td>
      <td><%= @user.created_at.localtime %></td>
    </tr>
  </tbody>
</table>

<div class="btn-grp">
  <%= (link_to "Edit Profile", edit_user_path, :class => "btn btn-default") if @user == current_user %>
  <%= (link_to "Create new blog post!", new_user_post_path(@user), :class => "btn btn-default") if @user == current_user %>
  <%= link_to "See blog posts!", user_posts_path(@user), :class => "btn btn-default" %>
  <%= (link_to "Create blog!", new_user_feed_path(@user), :class => "btn btn-default") if (@user == current_user) && !has_feed?(current_user) %>
  <%= link_to "Update blog info!", edit_user_feed_path(@user, @user.feed), :class => "btn btn-default" \
  if (@user == current_user) && has_feed?(current_user) %>
</div>